# Generated by Django 5.0.14 on 2026-09-04 09:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('preview_image_url', models.URLField(blank=True)),
                ('voice_model_id', models.CharField(max_length=100)),
                ('lip_sync_model', models.CharField(default='musetalk', max_length=50)),
                ('is_premium_only', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
