# Generated by Django 5.0.14 on 2026-09-04 09:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subjects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalCourse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(choices=[('linkedin_learning', 'LinkedIn Learning'), ('coursera', 'Coursera'), ('khan_academy', 'Khan Academy'), ('google_books', 'Google Books')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('url', models.URLField()),
                ('thumbnail_url', models.URLField(blank=True)),
                ('level', models.CharField(blank=True, max_length=20)),
                ('is_premium_only', models.BooleanField(default=False)),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='external_courses', to='subjects.subject')),
            ],
            options={
                'ordering': ['source', 'title'],
            },
        ),
        migrations.CreateModel(
            name='SavedExternalCourse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='integrations.externalcourse')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_external_courses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='externalcourse',
            index=models.Index(fields=['source', 'subject'], name='integration_source_801d08_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='savedexternalcourse',
            unique_together={('user', 'course')},
        ),
    ]
