# Generated by Django 5.0.14 on 2026-09-04 09:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(choices=[('payme', 'Payme'), ('click', 'Click')], max_length=10)),
                ('provider_transaction_id', models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ('amount_uzs', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=12)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('payme_state', models.SmallIntegerField(blank=True, null=True)),
                ('payme_create_time_ms', models.BigIntegerField(blank=True, null=True)),
                ('payme_perform_time_ms', models.BigIntegerField(blank=True, null=True)),
                ('payme_cancel_time_ms', models.BigIntegerField(blank=True, null=True)),
                ('payme_cancel_reason', models.SmallIntegerField(blank=True, null=True)),
                ('click_prepare_id', models.BigIntegerField(blank=True, null=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='accounts.subscriptionplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice_number', models.CharField(max_length=32, unique=True)),
                ('pdf_url', models.URLField(blank=True)),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='payments.paymenttransaction')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['user', 'status'], name='payments_pa_user_id_92d873_idx'),
        ),
    ]
